export const roles = [
  { id: "frontend-engineer", label: "Frontend Engineer" },
  { id: "backend-engineer", label: "Backend Engineer"},
  { id: "fullstack-engineer", label: "Full Stack Engineer"},
  { id: "ios-engineer", label: "iOS Engineer"},
  { id: "android-engineer", label: "Android Engineer" },
  { id: "data-scientist", label: "Data Scientist" },
  { id: "ux-designer", label: "UX Designer" },
  { id: "devops-engineer", label: "DevOps Engineer" },
]

export const skillsMap = {
  "frontend-engineer" : ["React", "TypeScript", "CSS", "Next.js", "Python", "Node.js", "Tailwind", "Bootstrap", "Swift", "Kubernetes", "Postgres"],
  "backend-engineer" : ["AWS", "Java", "Python", "SQL", "Docker", "Git", "Ruby", "JavaScript", "Go", "MongoDB", "Kafka", "Rest APIs", "Azure", "GraphQL"],
  "fullstack-engineer" : ["HTML", "CSS", "JavaScript", "TypeScript", "React", "Next.js", "Tailwind CSS", "Redux", "API", "Axios", "PostgreSQL", "MySQL"],
  "ios-engineer" : ["Swift", "SwiftUI", "Xcode", "Core Data", "UIKit"],
  "android-engineer" : ["Kotlin", "Java", "Jetpack Compose", "Android SDK", "Firebase"],
  "data-scientist" : ["Python", "Pandas", "PyTorch", "SQL", "Machine Learning", "Spark"],
  "ux-designer" : ["Figma", "User Research", "Prototyping", "Design Systems", "Accessibility"],
  "devops-engineer" : ["Docker", "Kubernetes", "AWS", "CI/CD", "Terraform", "Linux"]
}

export const usStates = [
  { id: "al", label: "Alabama" },
  { id: "ak", label: "Alaska" },
  { id: "az", label: "Arizona" },
  { id: "ar", label: "Arkansas" },
  { id: "ca", label: "California" },
  { id: "co", label: "Colorado" },
  { id: "ct", label: "Connecticut" },
  { id: "de", label: "Delaware" },
  { id: "fl", label: "Florida" },
  { id: "ga", label: "Georgia" },
  { id: "hi", label: "Hawaii" },
  { id: "id", label: "Idaho" },
  { id: "il", label: "Illinois" },
  { id: "in", label: "Indiana" },
  { id: "ia", label: "Iowa" },
  { id: "ks", label: "Kansas" },
  { id: "ky", label: "Kentucky" },
  { id: "la", label: "Louisiana" },
  { id: "me", label: "Maine" },
  { id: "md", label: "Maryland" },
  { id: "ma", label: "Massachusetts" },
  { id: "mi", label: "Michigan" },
  { id: "mn", label: "Minnesota" },
  { id: "ms", label: "Mississippi" },
  { id: "mo", label: "Missouri" },
  { id: "mt", label: "Montana" },
  { id: "ne", label: "Nebraska" },
  { id: "nv", label: "Nevada" },
  { id: "nh", label: "New Hampshire" },
  { id: "nj", label: "New Jersey" },
  { id: "nm", label: "New Mexico" },
  { id: "ny", label: "New York" },
  { id: "nc", label: "North Carolina" },
  { id: "nd", label: "North Dakota" },
  { id: "oh", label: "Ohio" },
  { id: "ok", label: "Oklahoma" },
  { id: "or", label: "Oregon" },
  { id: "pa", label: "Pennsylvania" },
  { id: "ri", label: "Rhode Island" },
  { id: "sc", label: "South Carolina" },
  { id: "sd", label: "South Dakota" },
  { id: "tn", label: "Tennessee" },
  { id: "tx", label: "Texas" },
  { id: "ut", label: "Utah" },
  { id: "vt", label: "Vermont" },
  { id: "va", label: "Virginia" },
  { id: "wa", label: "Washington" },
  { id: "wv", label: "West Virginia" },
  { id: "wi", label: "Wisconsin" },
  { id: "wy", label: "Wyoming" },
]

export const company = [
  { id: "linkedin", label: "Linkedin" },
  { id: "glassdoor", label: "Glassdoor" },
  { id: "indeed", label: "Indeed" },
  { id: "wellfound", label: "Wellfound" },
  { id: "handshake", label: "Handshake" },
  { id: "otta", label: "Otta" },
]